name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, bcmath, fileinfo
          coverage: none

      - name: ğŸ“¦ Install Composer dependencies
        working-directory: ./happy-place
        run: composer update --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: ğŸ”§ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ğŸ“¦ Install Node dependencies
        working-directory: ./happy-place
        run: npm ci

      - name: ğŸ—ï¸ Build frontend assets
        working-directory: ./happy-place
        run: npm run build

      - name: ğŸ¤ Zip Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'deploy.zip'
          directory: './happy-place'
          path: '.'
          exclusions: '*.git* /*node_modules/* /*tests/* /*storage/*.key'

      - name: ğŸ“‚ Upload Zip and Unzip Script
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          local-dir: ./happy-place/
          include: |
            deploy.zip
            unzip_deploy.php
          # We only upload these two files specifically, filtering out everything else to speed up
          exclude: |
            **

      - name: ğŸš€ Trigger Unzip on Server
        run: |
          echo "Triggering unzip on server..."
          curl -L "http://oodelivery.online/unzip_deploy.php"

